---
- name: Update all Windows hosts
  hosts: all
  tasks:
  - name: Update hosts with all available updates
    win_updates:
    register: update_result

  - name: reboot machine if the update requires it
    win_reboot:
      reboot_timeout: 3600
      msg: Reboot initiated by Ansible 
    when: update_result.reboot_required
        